name: "CI"

on:
  push:
    branches: ["**"]

  pull_request:
    branches: ["**"]

jobs:
  Linux:
    if: false
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      # Use "false" means a single failed build won't terminate other combinations
      # in the matrix. This wastes CPU time, so it's meant for debugging only.
      fail-fast: false

      matrix:
        os:
          # name: OS name (only a name for humans to read).
          # libc: userland libc, "GNU" or "musl"
          #       (only a name for humans to read)
          # ancient: true or false.
          #          true: incompatible with GitHub's actions/checkout due to
          #                node.js compatibility problem. Manual git checkout
          #                required.
          #          false: use standard GitHub's actions/checkout.
          # docker-image: string, image on DockerHub to use
          - name: "CentOS 7"
            libc: "GNU"
            ancient: true
            docker-image: "centos:7"

          - name: "Ubuntu 14.04"
            libc: "GNU"
            ancient: true
            docker-image: "ubuntu:14.04"

          - name: "Debian oldoldstable"
            libc: "GNU"
            ancient: false
            docker-image: "debian:oldoldstable"

          - name: "Debian oldstable"
            libc: "GNU"
            ancient: false
            docker-image: "debian:oldstable"

          - name: "Debian"
            libc: "GNU"
            ancient: false
            docker-image: "debian:latest"

          - name: "Ubuntu"
            libc: "GNU"
            ancient: false
            docker-image: "ubuntu:latest"

          - name: "Fedora"
            libc: "GNU"
            ancient: false
            docker-image: "fedora:latest"

          - name: "AlmaLinux 8"
            libc: "GNU"
            ancient: false
            docker-image: "almalinux:8"

          - name: "AlmaLinux 9"
            libc: "GNU"
            ancient: false
            docker-image: "almalinux:9"

          # Waiting for upstream packages:
          # https://bugzilla.redhat.com/show_bug.cgi?id=2374130
          # https://bugzilla.redhat.com/show_bug.cgi?id=2419727
          #
          #- name: "AlmaLinux Latest"
          #  libc: "GNU"
          #  ancient: false
          #  docker-image: "almalinux:latest"

          # GUI is not supported on Alpine as VTK is built without Qt
          - name: "Alpine, No GUI"
            libc: "musl"
            ancient: false
            docker-image: "alpine:latest"

    container:
      image: ${{ matrix.os.docker-image }}
      # allow mount/netns
      options: "--cap-add CAP_SYS_ADMIN --cap-add NET_ADMIN --security-opt apparmor=unconfined"

    name: "${{ matrix.os.libc }}/Linux (${{ matrix.os.name }})"

    steps:
      - name: Check for dockerenv file
        # bash is not installed on Alpine at this point
        shell: sh
        run: (ls /.dockerenv && echo Found dockerenv) || exit 1

      - name: Install dependencies
        shell: sh
        run: |
          cat /etc/os-release

          touch ~/.bash_profile  # set environment variables here

          # Use a strict shell, stop the interpreter on various errors,
          # so errors such as undefined variables are caught by CI/CD
          # instead of ignored. Use printf because it contains options,
          # which can be difficult to escape.
          printf "%s\n" "set -euo pipefail" >> ~/.bash_profile

          # For non-interactive shells such as "bash script.sh"
          # Use a special ~/.bash_env file because ~/.bash_profile
          # may contain commands that reset environment variables
          # such as PATH.
          printf "%s\n" "set -euo pipefail" >> ~/.bash_env
          echo 'export BASH_ENV="$HOME/.bash_env"' >> ~/.bash_profile
          echo 'export CXXFLAGS="-Wall -Wextra -Wno-error"' >> ~/.bash_profile

          if grep -q "ID=fedora" /etc/os-release; then
            dnf install -y git
            dnf install -y gcc gcc-c++ cmake git boost-devel tinyxml-devel vtk-devel hdf5-devel \
                           CGAL-devel vtk-qt octave python3-pip \
                           python3-setuptools python3-setuptools_scm \
                           python3-Cython python3-numpy python3-h5py python3-matplotlib

            # only for CI/CD test builds without networks.
            dnf install -y iproute
          elif grep -q 'ID="almalinux"' /etc/os-release; then
            dnf install -y epel-release
            dnf config-manager --set-enabled powertools || dnf config-manager --set-enabled crb

            dnf install -y git
            dnf install -y gcc gcc-c++ cmake git boost-devel tinyxml-devel vtk-devel hdf5-devel \
                           CGAL-devel vtk-qt octave python3-pip \
                           python3-setuptools python3-wheel python3-setuptools_scm \
                           python3-Cython python3-numpy python3-h5py python3-matplotlib

            # only for CI/CD test builds without networks.
            dnf install -y iproute
          elif grep -q "ID=debian" /etc/os-release || grep -q "ID=ubuntu" /etc/os-release; then
            # retry failed downloads 3 times
            echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries
            apt-get update

            apt-get install -y build-essential git \
                               libhdf5-dev libtinyxml-dev \
                               qtbase5-dev \
                               octave \
                               python3-pip \
                               python3-setuptools python3-numpy python3-matplotlib python3-h5py

            # VTK9 or VTK7, at least one must succeed (depending on Debian version)
            # VTK9,  VTK7, or VTK6, at least one must succeed (depending on Debian version)
            apt-get install -y libvtk9-dev libvtk9-qt-dev || \
                apt-get install -y libvtk7-dev libvtk7-qt-dev || \
                  apt-get install -y libvtk6-dev

            # only for CI/CD test builds without networks.
            apt-get install -y iproute2

            if grep -q 'VERSION_ID="14.04"' /etc/os-release; then
              # Ubuntu 14.04 has CMake 2 by default, but we require CMake 3
              apt-get install -y cmake3

              # Ubuntu 14.04 ships Boost 1.54 and is required by libcgal-dev,
              # but we need Boost 1.55, so we install Boost 1.55 first, then
              # install CGAL from source.
              apt-get install -y boost1.55 boost1.55-dev

              # CGAL v4.14.3 was old enough to be compatible with GCC 4.8. Otherwise,
              # you get: The compiler feature "cxx_decltype_auto" is not known
              # to CXX compiler "GNU" version 4.8.5.
              apt-get install -y libgmp-dev libmpfr-dev
              git clone $GITHUB_SERVER_URL/CGAL/cgal.git --depth=1 --branch=v4.14.3
              cd cgal && mkdir build && cd build
              cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/opt
              make -j`nproc` && make install

              # Must use Cython 3.0 or lower, since 3.1 uses f-string which is
              # incompatible with Python 3.4.
              pip3 install "cython<3.1"

              # Ubuntu 14.04's matplotlib package is ancient, install the
              # minimum version and its dependencies via pip. Note that the
              # native build uses Python 3.4 while the venv build (tested
              # later) uses Python 3.5 without these problems.
              #
              # pip's pyparsing is incompatible with Python 3.4
              apt-get install -y python3-pyparsing

              # same, newer cycler has incompatible type annotation
              pip3 install "cycler==0.10.0"
              pip3 install "matplotlib==2.1.0"
            else
              apt-get install -y libboost-all-dev
              apt-get install -y libcgal-dev
              apt-get install -y cmake
              apt-get install -y python3-setuptools-scm cython3 python3-matplotlib

              # testing Python packages in isolated venv
              apt-get install -y python3-venv
            fi
          elif grep -q "ID=alpine" /etc/os-release; then
            apk add bash \
                    build-base gmp-dev mpfr-dev git cmake \
                    boost-dev tinyxml-dev hdf5-dev cgal-dev vtk-dev \
                    octave \
                    python3-dev py3-pip \
                    py3-setuptools py3-setuptools_scm cython \
                    py3-numpy py3-h5py py3-matplotlib

            # only for CI/CD test builds without networks.
            apk add iproute2
          elif [ -f /etc/centos-release ]; then
            # IPv6 on GitHub Actions is broken, causing random network failures
            # if a CDN rosolves to IPv6.
            echo "ip_resolve=4" >> /etc/yum.conf

            # CentOS repos are EOL and desupported
            sed -i 's|^mirrorlist|#mirrorlist|g; s|^#baseurl|baseurl|g; s|mirror.centos.org|vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-Base.repo

            yum install -y centos-release-scl || true
            sed -i 's|^mirrorlist|#mirrorlist|g; s|^#baseurl|baseurl|g;
                    s|^# baseurl|baseurl|g; s|mirror.centos.org|vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-SCLo-scl.repo \
                /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
            cat /etc/yum.repos.d/CentOS-SCLo-scl.repo
            cat /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo

            yum install -y epel-release
            yum install -y git
            yum install -y gcc gcc-c++ gmp-devel mpfr-devel \
                           cmake3 git tinyxml-devel vtk-devel hdf5-devel octave \
                           python3-devel python3-pip \
                           python3-setuptools python3-setuptools_scm python3-Cython

            # only for CI/CD test builds without networks.
            yum install -y iproute

            # use cmake3 instead of default cmake2
            alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake3 99

            # To upgrade GCC, one can use GCC 7 from centos-release-scl, required by CGAL.
            # Even GCC 10+ is provided.
            # Not used for now, since openEMS is still compatible with GCC 4.8! But we may
            # need it in the future.
            # yum install -y devtoolset-7-gcc devtoolset-7-gcc-c++
            # alternatives --install /usr/local/bin/gcc gcc /opt/rh/devtoolset-7/root/usr/bin/gcc 99
            # alternatives --install /usr/local/bin/g++ g++ /opt/rh/devtoolset-7/root/usr/bin/g++ 99

            # boost-predef is only available on Boost 1.55 and later.
            #   /usr/local/include/CGAL/config.h:210:10: fatal error: boost/predef.h:
            #   No such file or directory
            # We borrow a copy of Boost 1.58 from rh repo's mariadb backport package.
            yum install -y rh-mariadb101-boost-devel

            # copy rh repo's Boost to /usr/local because CMake doesn't support CPATH
            ln -s /opt/rh/rh-mariadb101/root/usr/include/boost /usr/local/include/boost
            mkdir /usr/local/lib64 && cd /usr/local/lib64
            for i in /opt/rh/rh-mariadb101/root/usr/lib64/libboost*; do
                ln -s $i /usr/local/lib64/
            done

            # setup.py is broken on CentOS 7, installing openEMS shows:
            # error: Couldn't find a setup script in /tmp/easy_install-8fl5smm_/numpy-2.2.0.tar.gz
            # Error: Process completed with exit code 1.
            pip3 install numpy h5py matplotlib --user

            # not package on CentOS
            # CGAL v4.14.3 was old enough to be compatible with GCC 4.8. Otherwise,
            # you get: The compiler feature "cxx_decltype_auto" is not known
            # to CXX compiler "GNU" version 4.8.5.
            git clone $GITHUB_SERVER_URL/CGAL/cgal.git --depth=1 --branch=v4.14.3
            cd cgal && mkdir build && cd build
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/opt
            make -j`nproc` && make install
          else
            echo "Unknown system!"
            exit 1
          fi

          ip netns add no-network

      - if: ${{ ! matrix.os.ancient }}
        name: Checkout openEMS-Project.git
        uses: actions/checkout@v4
        with:
          path: openEMS-Project
          submodules: recursive

          # checkout must be deep, not shallow.
          # We need tags for "git describe", otherwise build fails.
          fetch-depth: 0

      - if: ${{ matrix.os.ancient }}
        name: Checkout openEMS-Project.git (legacy system only)
        run: |
          echo "Clone $GITHUB_SHA from $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"
          git clone --recursive $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git openEMS-Project
          cd $GITHUB_WORKSPACE/openEMS-Project

          # force git to fetch all trees, otherwise "git checkout $GITHUB_SHA"
          # fails with "fatal: reference is not a tree" for Pull Requests
          git fetch --force $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git "+refs/heads/*:refs/remotes/origin/*"
          git fetch --force $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git "+refs/pull/*/merge:refs/remotes/origin/pr/*"
          git checkout $GITHUB_SHA

          # update git submodules, because the Pull Request may change it
          git submodule init
          git submodule update

      - name: Build and install openEMS with --python-use-network=disable
        run: |
          source ~/.bash_profile
          cd $GITHUB_WORKSPACE/openEMS-Project

          # GUI is not supported on Alpine as VTK is built without Qt
          if grep -q "ID=alpine" /etc/os-release; then
            gui_opt="--disable-GUI"
          else
            gui_opt=""
          fi

          run_without_network="ip netns exec no-network"

          if $run_without_network \
             ./update_openEMS.sh ~/opt --python $gui_opt \
             --python-venv-mode=disable --python-use-network=disable
          then
            cat build_*.log
          else
            cat build_*.log
            exit 1
          fi

          echo "addpath('~/opt/share/openEMS/matlab')" >> ~/.octaverc
          echo "addpath('~/opt/share/CSXCAD/matlab')" >> ~/.octaverc

      - name: Smoketest Octave execution
        run: |
          cd $GITHUB_WORKSPACE/openEMS-Project/openEMS/.github/smoketests/octave
          octave MSL_NotchFilter.m

      - name: Smoketest Python execution
        run: |
          source ~/.bash_profile
          cd $GITHUB_WORKSPACE/openEMS-Project/openEMS/.github/smoketests/python
          python3 MSL_NotchFilter.py

      - name: Build and install openEMS in venv
        run: |
          cd $GITHUB_WORKSPACE/openEMS-Project

          # GUI is not supported on Alpine as VTK is built without Qt
          if grep -q "ID=alpine" /etc/os-release; then
            gui_opt="--disable-GUI"
          else
            gui_opt=""
          fi

          if grep -q "ID=ubuntu" /etc/os-release && \
            grep -q 'VERSION_ID="14.04"' /etc/os-release; then
              # Use Python 3.5 instead of the default Python 3.4 because
              # 3.5 is the latest available version on Ubuntu 14.04, and
              # also because Python 3.5 is the first Python that supported
              # type annotation, while Python 3.4 is locked out from most
              # modern packages.
              apt-get install -y curl python3.5-dev

              # Ubuntu 14.04 is ancient, and the python3.5-venv package is
              # broken. So the best approach is to install a bare Python 3.5
              # interpreter from apt, and bootstrapping pip ourselves.
              python3.5 -m venv ~/opt/venv --without-pip
              curl -O https://bootstrap.pypa.io/pip/3.5/get-pip.py
              source ~/opt/venv/bin/activate
              python3.5 get-pip.py
          fi

          # set it here because "source ~/venv/bin/activate" is
          # incompatible with set -euo pipefail
          source ~/.bash_profile
          if ./update_openEMS.sh ~/opt --python $gui_opt; then
            cat build_*.log
          else
            cat build_*.log
            exit 1
          fi

          echo "addpath('~/opt/share/openEMS/matlab')" >> ~/.octaverc
          echo "addpath('~/opt/share/CSXCAD/matlab')" >> ~/.octaverc

      - name: Smoketest Python execution in venv
        run: |
          source ~/opt/venv/bin/activate
          source ~/.bash_profile
          cd $GITHUB_WORKSPACE/openEMS-Project/openEMS/.github/smoketests/python
          python3 MSL_NotchFilter.py

  macOS:
    if: false
    name: "macOS (ARM, latest)"

    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          # Use a strict shell, stop the interpreter on various errors,
          # so errors such as undefined variables are caught by CI/CD
          # instead of ignored. Use printf because it contains options,
          # which can be difficult to escape.
          printf "%s\n" "set -euo pipefail" >> ~/.zprofile

          # For #!/bin/bash scripts.
          # To ensure ~/.bash_env is executed, BASH_ENV must be set for the
          # current default shell of which bash is launched from.
          # Use a special ~/.bash_env file because ~/.bash_profile
          # may contain commands that reset environment variables
          # such as PATH.
          printf "%s\n" "set -euo pipefail" >> ~/.bash_env
          echo 'export BASH_ENV="$HOME/.bash_env"' >> ~/.zprofile

          # GitHub's default ~/.bash_profile contains:
          #
          #     POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-macos15
          #
          # WITHOUT ending with "\n". Add a "\n" manually, otherwise
          # the command is invalid.
          printf "\n%s\n" "set -euo pipefail" >> ~/.bash_profile

          brew install cmake boost hdf5 cgal vtk octave qt5compat \
                       python3 \
                       python-setuptools numpy python-matplotlib cython

      - name: Checkout openEMS-Project.git
        uses: actions/checkout@v4
        with:
          path: openEMS-Project
          submodules: recursive

          # checkout must be deep, not shallow.
          # We need tags for "git describe", otherwise build fails.
          fetch-depth: 0

      - name: Build and install openEMS with --python-use-network=disable
        run: |
          source ~/.zprofile
          cd $GITHUB_WORKSPACE/openEMS-Project

          if ./update_openEMS.sh ~/opt --python \
             --python-venv-mode=disable --python-use-network=disable
          then
            cat build_*.log
          else
            cat build_*.log
            exit 1
          fi

          echo "addpath('~/opt/share/openEMS/matlab')" >> ~/.octaverc
          echo "addpath('~/opt/share/CSXCAD/matlab')" >> ~/.octaverc

      - name: Smoketest Octave execution
        run: |
          cd $GITHUB_WORKSPACE/openEMS-Project/openEMS/.github/smoketests/octave
          octave MSL_NotchFilter.m

      - name: Smoketest Python execution
        run: |
          cd $GITHUB_WORKSPACE/openEMS-Project/openEMS/.github/smoketests/python
          python3 MSL_NotchFilter.py

      - name: Build and install openEMS in venv
        run: |
          # remove Python dependencies to see if venv really works
          pip3 uninstall -y CSXCAD openEMS --break-system-packages
          brew remove python-setuptools cython numpy python-matplotlib

          source ~/.zprofile
          cd $GITHUB_WORKSPACE/openEMS-Project

          if ./update_openEMS.sh ~/opt --python; then
            cat build_*.log
          else
            cat build_*.log
            exit 1
          fi

      - name: Smoketest Python execution in venv
        run: |
          cd $GITHUB_WORKSPACE/openEMS-Project/openEMS/.github/smoketests/python
          source ~/opt/venv/bin/activate
          python3 MSL_NotchFilter.py

  FreeBSD:
    if: false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        machine:
          - name: "FreeBSD 14.2"
            os: freebsd
            arch: x86-64
            version: '14.2'

          # macOS already tests ARM for us, so disable the slow ARM emulator
          # for now
          #- name: "FreeBSD 14.2 (ARM emulator)"
          #  os: freebsd
          #  arch: arm64
          #  version: '14.2'

    name: "${{ matrix.machine.name }}"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

          # checkout must be deep, not shallow.
          # We need tags for "git describe", otherwise build fails.
          fetch-depth: 0

      - name: Test in FreeBSD ${{ matrix.machine.version }} ${{ matrix.machine.arch }}
        uses: cross-platform-actions/action@v0.26.0
        with:
          cpu_count: 4
          architecture: ${{ matrix.machine.arch }}
          operating_system: ${{ matrix.machine.os }}
          version: ${{ matrix.machine.version }}
          sync_files: runner-to-vm
          run: |
            echo "Install dependencies..."

            # use separate packages, not the meta-package "qt5" to save disk space
            sudo pkg install -y bash cmake git boost-libs tinyxml vtk9 hdf5 cgal octave \
                                qt5-core qt5-gui qt5-opengl qt5-xml \
                                python3 \
                                py311-pip py311-setuptools py311-wheel \
                                py311-cython3 py311-numpy py311-h5py py311-matplotlib
                                # prefix must match FreeBSD's default python
                                # version. FreeBSD 14.2 uses Python 3.11 so
                                # use "py311-"

            echo "Build and install openEMS with --python-use-network=disable..."

            if ./update_openEMS.sh ~/opt --python \
               --python-venv-mode=disable --python-use-network=disable
            then
              cat build_*.log
            else
              cat build_*.log
              exit 1
            fi

            echo "addpath('~/opt/share/openEMS/matlab')" >> ~/.octaverc
            echo "addpath('~/opt/share/CSXCAD/matlab')" >> ~/.octaverc

            echo "Smoketest Octave execution..."
            cd openEMS/.github/smoketests/octave/
            octave MSL_NotchFilter.m
            cd -

            echo "Smoketest Python execution..."
            cd openEMS/.github/smoketests/python
            python3 MSL_NotchFilter.py
            cd -

            echo "Build and install openEMS in venv..."
            # remove Python dependencies to see if venv really works
            pip uninstall -y CSXCAD openEMS --break-system-packages
            sudo pkg remove -y py311-pip \
                               py311-setuptools py311-wheel py311-setuptools-scm \
                               py311-cython3 py311-numpy py311-h5py py311-matplotlib

            if ./update_openEMS.sh ~/opt --python; then
              cat build_*.log
            else
              cat build_*.log
              exit 1
            fi

            echo "Smoketest Python execution in venv..."
            cd openEMS/.github/smoketests/python
            . ~/opt/venv/bin/activate
            python3 MSL_NotchFilter.py

  Windows:
    runs-on: windows-latest

    strategy:
      # Use "false" means a single failed build won't terminate other combinations
      # in the matrix. This wastes CPU time, but is an important debugging tool to
      # prevent a single broken platform from stopping the whole matrix.
      fail-fast: false

      matrix:
        toolchain:
          # name: toonchain name (only a name for humans to read).
          # CC, CXX: C/C++ compiler, environment variables
          # pkgmgr: vcpkg for per-commit testing, manual for official
          # binary releases because it allows targeting platforms
          # unsupported by vcpkg
          #- name: "MSVC"
          #  CC: "cl"
          #  CXX: "cl"
          #  pkgmgr: "vcpkg"
          #  build: "dev"

          #- name: "clang-cl"
          #  CC: "clang-cl"
          #  CXX: "clang-cl"
          #  pkgmgr: "vpkg"
          #  build: "dev"

          - name: "MSVC"
            CC: "cl"
            CXX: "cl"
            pkgmgr: "manual"
            build: "modern"

          - name: "clang-cl"
            CC: "clang-cl"
            CXX: "clang-cl"
            pkgmgr: "manual"
            build: "modern"

          - name: "MSVC"
            CC: "cl"
            CXX: "cl"
            pkgmgr: "manual"
            build: "legacy"

          - name: "clang-cl"
            CC: "clang-cl"
            CXX: "clang-cl"
            pkgmgr: "manual"
            build: "legacy"

    env:
      VS_ROOT_DIR: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/"
      CC: "${{ matrix.toolchain.CC }}"
      CXX: "${{ matrix.toolchain.CXX }}"
      CFLAGS: "/D_WIN32_WINNT=0x0601"
      CXXFLAGS: "/D_WIN32_WINNT=0x0601"
      PKGMGR: "${{ matrix.toolchain.pkgmgr }}"
      BUILD: "${{ matrix.toolchain.build }}"

      VCPKG_CACHE_PATH: "${{ github.workspace }}/vcpkg-cache/"
      VCPKG_BINARY_CACHE_PATH: "${{ github.workspace }}/vcpkg-cache/binary"
      VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/vcpkg-cache/binary,readwrite"
      VCPKG_ASSET_CACHE_PATH: "${{ github.workspace }}/vcpkg-cache/asset"
      X_VCPKG_ASSET_SOURCES: "x-azurl,file://${{ github.workspace }}/vcpkg-cache/asset,readwrite"

    name: "Windows (latest, ${{ matrix.toolchain.name }}, ${{ matrix.toolchain.build }}, ${{ matrix.toolchain.pkgmgr }})"

    steps:
      - name: Show checkout sources
        run: |
          echo "$env:FPARSER_CHECKOUT_TITLE"
          echo "$env:CSXCAD_CHECKOUT_TITLE"
        env:
          # convert template variables to shell variables to avoid arbitrary code injection
          FPARSER_CHECKOUT_TITLE: ${{ needs.Dependencies.outputs.fparser_checkout_title }}
          CSXCAD_CHECKOUT_TITLE: ${{ needs.Dependencies.outputs.csxcad_checkout_title }}

      # When checking out repos, I recommend running actions/checkout
      # as soon as possible before anything else, and in the reverse
      # order, from the project repo to its dependencies. This reduces
      # race conditions due to force pushes (they are harmless but
      # annoying).
      - name: Checkout openEMS-Project.git
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: openEMS-Project

          # checkout must be deep, not shallow.
          # We need tags for "git describe", otherwise build fails.
          fetch-depth: 0

      # It doesn't really work, because MSVC itself doesn't support long path.
      # But for future-proofing (it does work for clang).
      - name: Enable long paths
        run: |
          New-ItemProperty -Path "HKLM:/SYSTEM/CurrentControlSet/Control/FileSystem" `
                           -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Prepare download sources
        id: sources
        shell: python
        run: |
          from os import getenv


          PACKAGE_DICT = {
            "tinyxml": {
              "ver": "2.6.2",
              "dirname": "tinyxml",
              "tarball": "tinyxml_2_6_2.tar.gz",
              "url": "https://sourceforge.net/projects/tinyxml/files/tinyxml/$(ver)/$(tarball)",
            },
            "cgal": {
              "ver": "6.1",
              "dirname": "CGAL-$(ver)",
              "tarball": "$(dirname).tar.xz",
              "url": "$(github)/CGAL/cgal/releases/download/v$(ver)/$(tarball)"
            },
            "boost": {
              "ver": "1.90.0",
              "dirname": "boost-$(ver)",
              "tarball": "$(dirname)-cmake.tar.xz",
              "url": "$(github)/boostorg/boost/releases/download/boost-$(ver)/$(tarball)"
            },
            "hdf5": {
              "ver": "2.0.0",
              "dirname": "HDF5-$(ver)",
              "tarball": "$(ver).tar.gz",
              "url": "https://github.com/HDFGroup/hdf5/archive/refs/tags/$(tarball)"
            },
            "qt6_legacy": {
              "ver": "6.1.3",
              "shortver": "6.1",
              "dirname": "qt-everywhere-src-$(ver)",
              "tarball": "$(dirname).tar.xz",
              "url": "https://download.qt.io/archive/qt/6.1/6.1.3/single/$(tarball)"
            },
            "qt6_modern": {
              "ver": "6.10.1",
              "shortver": "6.10",
              "dirname": "qt-everywhere-src-$(ver)",
              "tarball": "$(dirname).tar.xz",
              "url": "https://download.qt.io/official_releases/qt/$(shortver)/$(ver)/single/$(tarball)"
            },
            "vtk": {
              "ver": "9.6.0.rc2",
              "dirname": "VTK-$(ver)",
              "tarball": "v$(ver).tar.gz",
              "url": "$(github)/Kitware/VTK/archive/refs/tags/$(tarball)"
            },
            # mesa-dist-win 25.2.6 is the last Win7 SP1+ version, see:
            # https://github.com/pal1000/mesa-dist-win/issues/233
            "mesa_legacy": {
              "ver": "25.2.6",
              # tarbomb, extract directly to the current directory
              "dirname": "./",
              "tarball": "mesa3d-$(ver)-release-msvc.7z",
              "url": "$(github)/pal1000/mesa-dist-win/releases/download/$(ver)/$(tarball)"
            },
            "mesa_modern": {
              "ver": "25.3.3",
              # tarbomb, extract directly to the current directory
              "dirname": "./",
              "tarball": "mesa3d-$(ver)-release-msvc.7z",
              "url": "$(github)/pal1000/mesa-dist-win/releases/download/$(ver)/$(tarball)"
            },
          }


          for name, prop in PACKAGE_DICT.items():
            dirname = prop["dirname"].replace("$(ver)", prop["ver"])
            if "shortver" in prop:
              dirname = dirname.replace("$(shortver)", prop["shortver"])

            tarball = prop["tarball"].replace("$(ver)", prop["ver"])
            tarball = tarball.replace("$(dirname)", dirname)

            url = prop["url"].replace("$(github)", getenv("GITHUB_SERVER_URL"))
            url = url.replace("$(ver)", prop["ver"])
            url = url.replace("$(tarball)", tarball)
            if "shortver" in prop:
              url = url.replace("$(shortver)", prop["shortver"])

            # to test locally, set:
            # export GITHUB_SERVER_URL="https://github.com"
            # export GITHUB_OUTPUT="/dev/stdout"
            with open(getenv("GITHUB_OUTPUT"), "a") as output:
              dirname_line = "%s_dirname=%s\n" % (name, dirname)
              tarball_line = "%s_tarball=%s\n" % (name, tarball)
              url_line = "%s_url=%s\n" % (name, url)

              # print but don't add more newlines
              print(dirname_line, end="")
              print(tarball_line, end="")
              print(url_line, end="")

              output.write(dirname_line)
              output.write(tarball_line)
              output.write(url_line)

      - name: (manual) Download dependencies
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          mkdir -p $HOME/code/downloads && cd $HOME/code/downloads
          mkdir -p $HOME/code/opt
          mkdir -p $HOME/code/build

          # TODO: sha256sum to prevent malware
          $curl_args = (
            "-L",                 # follow redirect
            "--fail",             # fail if 404
            "--fail-early",       # fail if any of the link is a 404
                                  # by default, a later success overrides the fail
            "--remote-name-all",  # use auto filenames

            # TinyXML with special cases
            # The first patch enforces use of stl strings, rather than a custom string type.
            # The second patch is a fix for incorrect encoding of elements with special characters.
            # The third and fourth patches are security fixes.
            # The final patch introduces a CMake build file
            "${{ steps.sources.outputs.tinyxml_url }}",
            "https://raw.githubusercontent.com/alpinelinux/aports/b1ff376e83eb49c0127b039b3684eccdf9a60694/community/tinyxml/tinyxml-2.6.2-defineSTL.patch",
            "https://raw.githubusercontent.com/alpinelinux/aports/b1ff376e83eb49c0127b039b3684eccdf9a60694/community/tinyxml/tinyxml-2.6.1-entity.patch",
            "https://raw.githubusercontent.com/alpinelinux/aports/b1ff376e83eb49c0127b039b3684eccdf9a60694/community/tinyxml/CVE-2021-42260.patch",
            "https://raw.githubusercontent.com/alpinelinux/aports/b1ff376e83eb49c0127b039b3684eccdf9a60694/community/tinyxml/CVE-2023-34194.patch",
            "https://gist.githubusercontent.com/scpeters/6325123/raw/cfb079be67997cb19a1aee60449714a1dedefed5/tinyxml_CMakeLists.patch",

            # Qt 6 legacy with special cases
            # Both patches allow building qt5compat without optional dependencies
            "${{ steps.sources.outputs.qt6_legacy_url }}",
            "https://github.com/qt/qt5/commit/81096b44bb183772c979debca2ffd1f8b364bbc8.patch",
            "https://github.com/qt/qt5compat/commit/307d82ee13b68a4ffd488709fb948d37f04b096b.patch",

            # qsharedpointer_impl.h(668,77): error: no member named 'data' in 'QWeakPointer<T>'
            # under clang
            "https://github.com/qt/qtbase/commit/0e4cc15da330fb25b913fbc8089e60f80a08f49f.patch",

            "${{ steps.sources.outputs.mesa_legacy_url }}",
            "${{ steps.sources.outputs.mesa_modern_url }}",
            "${{ steps.sources.outputs.cgal_url }}",
            "${{ steps.sources.outputs.boost_url }}",
            "${{ steps.sources.outputs.hdf5_url }}",
            "${{ steps.sources.outputs.qt6_modern_url }}",
            "${{ steps.sources.outputs.vtk_url }}"
          )

          echo "Downloading $curl_args"
          curl.exe -L $curl_args

      - name: (manual) Build and install TinyXML
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          & "$env:VS_ROOT_DIR/Common7/Tools/Launch-VsDevShell.ps1" -Arch amd64 -HostArch amd64

          cd $HOME/code/build
          tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.tinyxml_tarball }}"
          cd "${{ steps.sources.outputs.tinyxml_dirname }}"

          # The first patch enforces use of stl strings, rather than a custom string type.
          # The second patch is a fix for incorrect encoding of elements with special characters
          # The third and fourth patches are security fixes.
          cat $HOME/code/downloads/tinyxml-2.6.2-defineSTL.patch | patch -p1
          cat $HOME/code/downloads/tinyxml-2.6.1-entity.patch | patch -p1
          cat $HOME/code/downloads/CVE-2021-42260.patch | patch -p1
          cat $HOME/code/downloads/CVE-2023-34194.patch | patch -p1

          # The final patch adds a CMakeLists.txt file to build a shared library and
          # provide an install target
          cat $HOME/code/downloads/tinyxml_CMakeLists.patch | patch -p1

          # You know something is truly deprecated when the patch itself needs
          # patching! In CMake 4, 3.10 is deprecated and 3.5 has been removed.
          # Replace "cmake_minimum_required(VERSION 2.4.6)" in the patch with
          # "cmake_minimum_required(VERSION 3.0...3.10)". The newline must also
          # appear before PROJECT(), so run a insert-delete instead of a replace.
          sed -i -e "1i cmake_minimum_required(VERSION 3.0...3.10)" `
                 -e "1i project(tinyxml CXX)" `
                 -e "/cmake_minimum_required(VERSION 2.4.6)/d" `
                 CMakeLists.txt

          mkdir build && cd build

          cmake ../ -GNinja -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON `
                    -DCMAKE_BUILD_TYPE=Release `
                    -DCMAKE_INSTALL_PREFIX="$HOME/opt/"

          cmake --build ./ --parallel
          cmake --install ./ --parallel 8

      - name: (manual) Build and install CGAL
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          & "$env:VS_ROOT_DIR/Common7/Tools/Launch-VsDevShell.ps1" -Arch amd64 -HostArch amd64

          cd $HOME/code/build
          tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.cgal_tarball }}"
          cd "${{ steps.sources.outputs.cgal_dirname }}"
          mkdir build && cd build

          cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release `
                    -DCMAKE_INSTALL_PREFIX="$HOME/opt/"

          cmake --build . --parallel
          cmake --install . --parallel 8

      - name: (manual) Build and install Boost
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          & "$env:VS_ROOT_DIR/Common7/Tools/Launch-VsDevShell.ps1" -Arch amd64 -HostArch amd64

          cd $HOME/code/build
          tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.boost_tarball }}"
          cd "${{ steps.sources.outputs.boost_dirname }}"
          mkdir build && cd build

          cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release `
                    -DBOOST_USE_WINAPI_VERSION="0x0601"  `
                    -DBOOST_EXCLUDE_LIBRARIES="log" `
                    -DCMAKE_INSTALL_PREFIX="$HOME/opt/"

          cmake --build . --parallel
          cmake --install . --parallel 8

      - name: (manual) Build and install HDF5
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          & "$env:VS_ROOT_DIR/Common7/Tools/Launch-VsDevShell.ps1" -Arch amd64 -HostArch amd64

          cd $HOME/code/build
          tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.hdf5_tarball }}"
          cd "${{ steps.sources.outputs.hdf5_dirname }}"

          mkdir build && cd build

          cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release `
                    -DCMAKE_INSTALL_PREFIX="$HOME/opt/"

          cmake --build . --parallel
          cmake --install . --parallel 8
        env:
          # only works with MSVC
          CC: cl
          CXX: cl

      - name: (manual) Build and install Qt 6
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          & "$env:VS_ROOT_DIR/Common7/Tools/Launch-VsDevShell.ps1" -Arch amd64 -HostArch amd64

          cd $HOME/code/build

          if ($env:BUILD -eq "legacy") {
            # rename Qt 6 directory to avoid path long problem.
            tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.qt6_legacy_tarball }}"
            mv "${{ steps.sources.outputs.qt6_legacy_dirname }}" qt6
            cd qt6

            # allow building qt5compat without optional dependencies
            cat $HOME/code/downloads/81096b44bb183772c979debca2ffd1f8b364bbc8.patch |
              patch -p1

            # Use fuzz match for second patch, because the file content in git and
            # stable version slightly differs.
            cat $HOME/code/downloads/307d82ee13b68a4ffd488709fb948d37f04b096b.patch |
              patch -p1 --fuzz 5 -d qt5compat

            # qsharedpointer_impl.h(668,77): error: no member named 'data' in 'QWeakPointer<T>'
            # under clang
            cat $HOME/code/downloads/0e4cc15da330fb25b913fbc8089e60f80a08f49f.patch |
              patch -p1 -d qtbase
          }
          elseif ($env:BUILD -eq "modern") {
            # rename Qt 6 directory to avoid path long problem.
            tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.qt6_modern_tarball }}"
            mv "${{ steps.sources.outputs.qt6_modern_dirname }}" qt6
            cd qt6
          }
          else {
            exit 1
          }

          mkdir build && cd build

          if ($env:BUILD -eq "legacy") {
            # only build qtbase,qt5compat
            $opt = (
              "-cmake-generator", "Ninja",
              "-release",
              "-nomake", "examples",
              "-skip", "qt3d",              "-skip", "qtactiveqt",
              "-skip", "qtcharts",          "-skip", "qtcoap",
              "-skip", "qtdatavis3d",       "-skip", "qtdeclarative",
              "-skip", "qtdoc",             "-skip", "qtimageformats",
              "-skip", "qtlottie",          "-skip", "qtmqtt",
              "-skip", "qtnetworkauth",     "-skip", "qtopcua",
              "-skip", "qtquick3d",         "-skip", "qtquickcontrols2",
              "-skip", "qtquicktimeline",   "-skip", "qtscxml",
              "-skip", "qtshadertools",     "-skip", "qtsvg",
              "-skip", "qttools",           "-skip", "qttranslations",
              "-skip", "qtvirtualkeyboard", "-skip", "qtwayland"
            )

            # not compatible with clang-cl, only works with MSVC
            $env:CC="cl"
            $env:CXX="cl"
          }
          elseif ($env:BUILD -eq "modern") {
            # QML (qtdeclarative, or Qt Quick) is a heavy JavaScript GUI
            # engine, which is NOT used by QCSXCAD/AppCSXCAD, disable it.
            $opt = (
              "-nomake", "examples",
              "-skip", "qtdeclarative",
              "-submodules", "qtbase,qt5compat"
            )
          }
          else {
            exit 1
          }

          ../configure.bat -prefix "$HOME/opt/" $opt

          cmake --build . --parallel
          cmake --install . --parallel 8

        env:
          # Qt 6 uses Win8.1+ features, set to 0x0602 to avoid build failures.
          CFLAGS: "/D_WIN32_WINNT=0x0602"
          CXXFLAGS: "/D_WIN32_WINNT=0x0602"

      - name: (manual) Build and install VTK
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          & "$env:VS_ROOT_DIR/Common7/Tools/Launch-VsDevShell.ps1" -Arch amd64 -HostArch amd64

          cd $HOME/code/build
          tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.vtk_tarball }}"
          cd "${{ steps.sources.outputs.vtk_dirname }}"

          mkdir build && cd build

          # QML (qtdeclarative, or Qt Quick) is a heavy JavaScript GUI
          # engine, which is NOT used by QCSXCAD/AppCSXCAD, disable it.
          cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release  `
                  -DVTK_MODULE_ENABLE_VTK_GUISupportQt=WANT `
                  -DVTK_MODULE_ENABLE_VTK_GUISupportQtQuick=DONT_WANT `
                  -DVTK_MODULE_ENABLE_VTK_GUISupportQtSQL=DONT_WANT `
                  -DCMAKE_INSTALL_PREFIX="$HOME/opt/"

          cmake --build . --parallel
          cmake --install . --parallel 8

        env:
          # only works with MSVC
          CC: cl
          CXX: cl

      - name: (vcpkg) Download and install dependencies
        if: matrix.toolchain.pkgmgr == 'vcpkg'
        run: |
          # hack, will be removed
          cd $env:GITHUB_WORKSPACE/openEMS-Project/QCSXCAD
          vcpkg new --application
          vcpkg add port boost cgal hdf5 tinyxml
          vcpkg add port qtbase qt5compat vtk[qt]

          cd $env:GITHUB_WORKSPACE/openEMS-Project/AppCSXCAD
          vcpkg new --application
          vcpkg add port boost cgal hdf5 tinyxml
          vcpkg add port qtbase qt5compat vtk[qt]

      - name: Build and install openEMS
        run: |
          & "$env:VS_ROOT_DIR/Common7/Tools/Launch-VsDevShell.ps1" -Arch amd64 -HostArch amd64

          cd $env:GITHUB_WORKSPACE/openEMS-Project

          # hack, to be committed into fparser codebase
          sed -i -e "1i set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)" `
                    fparser/CMakeLists.txt

          mkdir build

          # We want a short path to work around MSVC's path limitation
          # but it cannot be too short! CMake has a bug that generates
          # a broken Ninja build file if the build directory is a drive's
          # root directory!
          #
          # https://gitlab.kitware.com/cmake/cmake/-/issues/20404
          # https://github.com/ninja-build/ninja/issues/1747
          subst X: (Resolve-Path ./)
          cd X:/build

          if ($env:PKGMGR -eq "manual") {
            cmake "$env:GITHUB_WORKSPACE/openEMS-Project" `
                  -GNinja -DCMAKE_BUILD_TYPE=Release `
                  -DCMAKE_INSTALL_PREFIX="$HOME/opt/"
          }
          elseif ($env:PKGMGR -eq "vcpkg") {
            cmake "$env:GITHUB_WORKSPACE/openEMS-Project" `
                  -GNinja -DCMAKE_BUILD_TYPE=Release `
                  -DCMAKE_INSTALL_PREFIX="$HOME/opt/" `
                  -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
                  -DVCPKG_HOST_TRIPLET="x64-windows-release" `
                  -DVCPKG_TARGET_TRIPLET="x64-windows-release" `
                  -DVCPKG_INSTALL_OPTIONS="--x-buildtrees-root=C:/vctree;--clean-buildtrees-after-build"
          }
          else {
            exit 1
          }

          cmake --build ./ --parallel --verbose
          cmake --install ./ --parallel 8

      - name: (manual) Bundle openEMS DLLs
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          cp $HOME/opt/lib/tinyxml.dll $HOME/opt/bin/
          cp $HOME/opt/lib/fparser.dll $HOME/opt/bin/
          cp $HOME/opt/lib/CSXCAD.dll $HOME/opt/bin/
          cp $HOME/opt/lib/QCSXCAD.dll $HOME/opt/bin/

      - name: (manual) Bundle Windows Universal CRT
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          # ignored on Windows 10+ in favor of OS's UCRT, but needed on
          # Windows 7 SP1+.
          & "$env:VS_ROOT_DIR/Common7/Tools/Launch-VsDevShell.ps1" -Arch amd64 -HostArch amd64
          cp $env:WindowsSdkDir/Redist/ucrt/DLLs/x64/* $HOME/opt/bin/

      - name: (manual) Bundle Mesa
        if: matrix.toolchain.pkgmgr == 'manual'
        run: |
          cd ~/code

          # tarbomb, extract many files directly to the current directory
          # make sure we're already in a safe subdirectory
          mkdir mesa3d
          cd mesa3d

          if ($env:BUILD -eq "legacy") {
            tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.mesa_legacy_tarball }}"
          }
          elseif ($env:BUILD -eq "modern") {
            tar -xf "$HOME/code/downloads/${{ steps.sources.outputs.mesa_modern_tarball }}"
          }
          else {
            exit 1
          }
          ls

          cp ./x64/libgallium_wgl.dll $HOME/opt/bin/
          cp ./x64/opengl32.dll $HOME/opt/bin/
          cp ./x64/dxil.dll $HOME/opt/bin/

      - name: Upload build artifacts
        if: matrix.toolchain.pkgmgr == 'manual'
        uses: actions/upload-artifact@v4
        with:
          name: openems-windows-${{ matrix.toolchain.name }}-${{ matrix.toolchain.build }}-${{ github.sha }}
          path: ~/opt/
